### ISSUE TITLE
AWSSDK.DynamoDB.Sample:ContactManager.iOS crashes on "Facebook Login" tap

### ISSUE THREAD

**Issue by airpaulg** [awslabs/aws-sdk-net-samples#1]
Error:
Objective-C exception thrown.  Name: InvalidOperationException Reason: fb is not registered as a URL scheme. Please add it in your Info.plist

I tried changed the infos in Info.plist with my own Facebook app id and it didn't work either. I tried adding the properties suggested in this Stack answer and that didn't work too: http://stackoverflow.com/questions/21893447/facebook-sdk-app-not-registered-as-a-url-scheme

**Comment by airpaulg** [comment]
I might have found part of the problem. While the App ID is in the URL Schemes in Info.plist, it has been omitted in the Constants.cs file (FB_APP_ID = ""). 

I changed that to FB_APP_ID = "809434219126221".

Now, instead of crashing, I get this:

˜
![screen shot 2015-08-26 at 4 38 35 pm](https://cloud.githubusercontent.com/assets/2952404/9505518/eda4fbec-4c10-11e5-99ed-fea550b8a67d.png)

**Comment by airpaulg** [comment]
I created my own facebook app in Prod, switched the infos in the sample to my own and now I get a ArgumentNullException on

App.OnFacebookAuthSuccess(accessToken.TokenString);

because identityPoolId is null. This makes sense since, again in Constants.CS,
public const string COGNITO_IDENTITY_POOL_ID = ""; 

Is the sample meant to be usable? I keep facing one problem after the other.

**Comment by karthiksaligrama** [comment]
Hi,

you are required to update the constants.cs information. It looks like the readme is missing. I'll add a readme with the setup information.

**Comment by airpaulg** [comment]
Ok thanks Karthik, this makes much more sense.

**Comment by georgeedwards** [comment]
@airpaulg How did you resolve the 

> App not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.
>  error? I have filled in the constants, but still get that error, even when using a registered test user from my Facebook developer account?

**Comment by DarnelleF** [comment]
readme is missing for dynamodb sample

**Comment by rubyrose-alexis** [comment]
Sorry for the delayed reply. This issue has been fixed with the PR https://github.com/awslabs/aws-sdk-net-samples/pull/15.
